CREATE DATABASE IF NOT EXISTS `COD` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `COD`;

CREATE TABLE `RATIO` (
  `date` TIMESTAMP,
  `value` FLOAT,
  PRIMARY KEY (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;