CREATE DATABASE IF NOT EXISTS `COD` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `COD`;

CREATE TABLE `RATIO` (
  `date` TIMESTAMP,
  `value` FLOAT,
  PRIMARY KEY (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `HEADSHOTS` (
  `date` TIMESTAMP,
  `value` FLOAT,
  PRIMARY KEY (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `GAMETIME` (
  `date` TIMESTAMP,
  `value` INTEGER,
  PRIMARY KEY (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MATCHES` (
  `date` TIMESTAMP,
  `value` INTEGER,
  PRIMARY KEY (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `DEATHS` (
  `date` TIMESTAMP,
  `value` INTEGER,
  PRIMARY KEY (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `KILLS` (
  `date` TIMESTAMP,
  `value` INTEGER,
  PRIMARY KEY (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `WALLBANGS` (
  `date` TIMESTAMP,
  `value` INTEGER,
  PRIMARY KEY (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;